[application]

[web.app]

# HTML title tag content
title = "demrec"

# Base path for assets when deployed to subdirectory
base_path = "/demrec/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
